export enum ScreenNames {
  MAIN_TABS='MAIN_TABS',
  PLACE_DETAILS_STACK='PLACE_DETAILS_STACK',
  EVENTS_STACK='EVENTS_STACK',
  SETTINGS_STACK='SETTINGS_STACK',
  GAME_STACK='GAME_STACK',
  GAME_PLAY_SCREEN='GAME_PLAY_SCREEN',

  PLACES_SCREEN='PLACES_SCREEN',
  EVENTS_SCREEN='EVENTS_SCREEN',
  GAME_SCREEN='GAME_SCREEN',
  SETTINGS_SCREEN='SETTINGS_SCREEN',

  PLACE_INFO_SCREEN='PLACE_INFO_SCREEN',
  MAP_SCREEN='MAP_SCREEN',
  MY_EVENTS_SCREEN='MY_EVENTS_SCREEN',
  EVENT_INFO_SCREEN='EVENT_INFO_SCREEN',
  ADD_EVENT_SCREEN='ADD_EVENT_SCREEN',
  EDIT_EVENT_SCREEN='EDIT_EVENT_SCREEN',
  GAME_SCORE_SCREEN='GAME_SCORE_SCREEN',
  FAVORITES_SCREEN='FAVORITES_SCREEN',
  STATS_SCREEN='STATS_SCREEN',
}
